package com.example.seurity.service;
import com.example.seurity.dto.RegisterUserDto;
import com.example.seurity.dto.SimpleRegistrationRequest;
import com.example.seurity.entity.Roles;
import com.example.seurity.entity.User;
import com.example.seurity.repo.RoleRepository;
import com.example.seurity.repo.UserRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.Optional;

@Service
public class RegistrationService {

    private static final Logger logger = LoggerFactory.getLogger(RegistrationService.class);

    @Autowired
    private AuthenticationService userService;

    @Autowired
    private UserRepository userRepository;

    @Autowired
    private RoleRepository roleRepository;

    /**
     * Simple registration for Workforce or Organization users
     * Creates a user account and sends activation email with auto-generated password
     */
    @Transactional
    public Map<String, Object> registerSimple(SimpleRegistrationRequest request) {
        Map<String, Object> response = new HashMap<>();

        logger.info("Processing simple registration for email: {}", request.getEmail());

        // Check if email already exists
        if (userRepository.existsByEmail(request.getEmail())) {
            throw new RuntimeException("Email already registered: " + request.getEmail());
        }

        // Determine role based on registration type

        String roleName;
        if ("WORKFORCE".equalsIgnoreCase(request.getRegistrationType())) {
            roleName = "ADMIN";     // ID 1
        } else if ("ORGANIZATION".equalsIgnoreCase(request.getRegistrationType())) {
            roleName = "STAFF";    // ID 4
        } else if ("ORDER".equalsIgnoreCase(request.getRegistrationType())) {
            roleName = "CLIENT";     // ID 2 (Maps ORDER request to STAFF role)
        } else if ("STORE".equalsIgnoreCase(request.getRegistrationType())) {
            roleName = "STORE";     // ID 3
        } else {
            throw new RuntimeException("Invalid registration type: " + request.getRegistrationType());
        }

        // Find the role in the database
        Optional<Roles> role = roleRepository.findByRoleName(roleName);
        if (!role.isPresent()) {
            throw new RuntimeException("Role '" + roleName + "' not found in database. Please check your roles table.");
        }

        // Create RegisterUserDto from simple request
        RegisterUserDto userDto = new RegisterUserDto();
        userDto.setFirstName(request.getFirstName());
        userDto.setSecondName(request.getMiddleName()); // middleName maps to secondName
        userDto.setLastName(request.getLastName());
        userDto.setEmail(request.getEmail());
        userDto.setUsername(request.getEmail()); // Use email as username
        userDto.setPhoneNumber(request.getPhoneNumber());
        userDto.setRoleId(role.get().getRoleId());
        // Password will be auto-generated by AuthenticationService

        // Create user (this will auto-generate password and send email)
        User user = userService.signup(userDto);

        response.put("message", "Registration successful! Please check your email to activate your account.");
        response.put("userId", user.getUserId());
        response.put("email", user.getEmail());
        response.put("registrationType", request.getRegistrationType());
        response.put("roleName", roleName);

        logger.info("Simple registration completed for user: {}", user.getUserId());

        return response;
    }
}

